name=ArduRoomba
version=3.2.0
author=Preetham Kyanam <preetham@preetham.org>
maintainer=Preetham Kyanam <preetham@preetham.org>
sentence=Complete Arduino library for iRobot Roomba control with WiFi, Bluetooth, and smart home support.
paragraph=The definitive library for breathing new life into legacy iRobot Roomba robots. Full Open Interface support with WiFi web control, Bluetooth LE, Home Assistant MQTT, and Amazon Alexa voice control. Turn e-waste into smart robots.
category=Device Control
url=https://github.com/pkyanam/ArduRoomba
license=MIT
architectures=avr,renesas_uno,esp8266,esp32
includes=ArduRoomba.h